excerpt_link: Read More
img:
    favicon: https://www.anotherhome.net/wp-content/themes/Amativeness/favicon.ico
    head4: https://diygod.b0.upaiyun.com/head4.jpg
    avatar: https://coding.net/u/sfantree/p/blogimage/git/raw/master/theme/main.jpg
    footerimg: https://ooo.0o0.ooo/2017/01/22/58844049efc47.png
    xm: https://ooo.0o0.ooo/2017/01/22/588436c306f69.png

predns:
    coding: cdn.coding.net
    ms.sm: ooo.0o0.ooo

menu:
  home:
    text: 主页
    url: /
  archives:
    text: 归档
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  github:
    text: 项目
    url: https://github.com/
    target: _blank
  weibo:
    text: 微波
    url: http://www.weibo.com/
    target: _blank
  link:
    text: 链接
    url: /links



